### ISSUE TITLE
review: Chapter1

### ISSUE THREAD

**Issue by underfirst** [amanotaiga/2020_nlp100knock#1]
You are fast at work and code is good. I have small advice and find misunderstanding.

# 00: reversed string

the other solution I know.

```python
print("".join(reversed(s))
```

## 03 Pi

`s.split(" ")` return list. So the line `words = [w for w in s.split(' ')]` can replace ``words = s.split(' ')`

## 08. cipher text

The problem's "c" is not the character "c" itself. It refers all the alphabetical letter.
Also, you need to create decipher function.

# 09. 09. Typoglycemia

It might have bug or misunderstanding. 
In my understanding, the problem's "shuffle" means permute middle part of the word. For example, shuffling the word "believe", it should start "b" and have "e", "l", "i", "e", "v" and end with "e". But, your answer example does not have "v".

Part of your answer output
>I clnoudt bileee that I cuod atcauly urasdnetd what I was r...

**Comment by amanotaiga** [comment]
add your advice and fix bugs of problem 09
